### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xEricL** [nootify/PinguBot#16]
Hi there!

Just wanted to ask, is the docker stack operational yet? Just reading through the Dockerfiles and the docker-compose.yml file and I'm not very familiar with the way you set things up. 

Not saying you did anything wrong, I just want to make sure I'm not learning from something that isn't ready to be used yet.

Thanks!
Eric

**Comment by nootify** [comment]
Hello! So... I wasn't expecting anyone to actually look at this repository. lol

I based most of the bot's Dockerfile off of this: https://github.com/python-poetry/poetry/discussions/1879#discussioncomment-216865
It would have been nice to have an official image of poetry to work off of, but for now this boilerplate is here to stay.

The lavalink Dockerfile is a workaround to avoid using a volume mount since the lavalink server only takes in a configuration file and no environment variables sadly.

The docker-compose setup should work out of the box as long as the `.env` file is in good shape.
