### ISSUE TITLE
Clown Election 2020

### ISSUE THREAD

**Issue by gabbyrose** [nootify/PinguBot#6]
![CD663CBD-6111-45CD-99B1-62D4820B429C](https://user-images.githubusercontent.com/73755385/97786113-b5cf7280-1b7f-11eb-9d2a-a0b8211eade1.png)

**Comment by nootify** [comment]
I wanted to do this originally, but I ran into a problem where someone's name has a space. I made it only nominate one user at a time because of [the way how the bot processes a command](https://github.com/nootify/PinguBot/blob/2dbda5925c0681643bf3eb3c2c751ab29c5039a5/cogs/clown.py#L114).

I like the idea of the comma delimiter, but I want to avoid making the command too complex to use or error-prone because of typos.

**Comment by nootify** [comment]
After some consideration: the command can only take one poll at a time in a server to prevent race conditions. Will reopen if alternative solution can be found.
